raw_data_root: storage/data/dstc8-schema-guided-dialogue
data_prep_out_root: storage/processed_data/simple_tod
context_type: nlg_api_call
chatgpt_results_path: data_exploration/chatgpt/chat_gpt_all sgd.csv
